package saalispaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import saalispaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.29 20:22:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkintaTest {


  // Generated by ComTest BEGIN
  /** testAseta120 */
  @Test
  public void testAseta120() {    // Merkinta: 120
    Merkinta m1 = new Merkinta(); 
    assertEquals("From: Merkinta line: 122", null, m1.aseta(1, "20.11.2020")); 
    assertEquals("From: Merkinta line: 123", "Liian suuri päivämäärä", m1.aseta(1, "40.11.2020")); 
    assertEquals("From: Merkinta line: 124", "Liian pieni päivämäärä", m1.aseta(1, "00.11.2020")); 
    assertEquals("From: Merkinta line: 125", null, m1.aseta(2, "Mikitänjärvi")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi210 */
  @Test
  public void testRekisteroi210() {    // Merkinta: 210
    Merkinta m1 = new Merkinta(); 
    assertEquals("From: Merkinta line: 212", 0, m1.getTunnusNro()); 
    m1.rekisteroi(); 
    Merkinta m2 = new Merkinta(); 
    m2.rekisteroi(); 
    int n1 = m1.getTunnusNro(); 
    int n2 = m2.getTunnusNro(); 
    assertEquals("From: Merkinta line: 218", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString252 */
  @Test
  public void testToString252() {    // Merkinta: 252
    Merkinta merkinta = new Merkinta(); 
    merkinta.parse("   1  |  29.1.2018   | Mikitänjärvi |  Poutaa  |"); 
    assertEquals("From: Merkinta line: 255", false, merkinta.toString().startsWith("1|29.1.2018|Mikitänjärvi|Poutaa|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse276 */
  @Test
  public void testParse276() {    // Merkinta: 276
    Merkinta merkinta = new Merkinta(); 
    merkinta.parse("    1  |  29.1.2018   | Mikitänjärvi |  Poutaa  |"); 
    assertEquals("From: Merkinta line: 279", 1, merkinta.getTunnusNro()); 
    assertEquals("From: Merkinta line: 280", false, merkinta.toString().startsWith("1|29.1.2018|Mikitänjärvi|Poutaa|")); 
    merkinta.rekisteroi(); 
    int n = merkinta.getTunnusNro(); 
    merkinta.parse(""+(n+1)); 
    merkinta.rekisteroi(); 
    assertEquals("From: Merkinta line: 286", n+1+1, merkinta.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone299 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone299() throws CloneNotSupportedException {    // Merkinta: 299
    Merkinta m = new Merkinta(); 
    m.parse("   1  |  20.11.1995   | 1"); 
    Merkinta kopio = m.clone(); 
    assertEquals("From: Merkinta line: 304", m.toString(), kopio.toString()); 
    m.parse("   2  |  21.11.1944   | 1"); 
    assertEquals("From: Merkinta line: 306", false, kopio.toString().equals(m.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals323 */
  @Test
  public void testEquals323() {    // Merkinta: 323
    Merkinta m1 = new Merkinta(); 
    m1.parse("   1  | 20.11.1995  | 1"); 
    Merkinta m2 = new Merkinta(); 
    m2.parse("   1  | 20.11.1995  | 1"); 
    Merkinta m3 = new Merkinta(); 
    m3.parse("   1  | 20.11.1996  | 1"); 
    assertEquals("From: Merkinta line: 331", true, m1.equals(m2)); 
    assertEquals("From: Merkinta line: 332", true, m2.equals(m1)); 
    assertEquals("From: Merkinta line: 333", false, m1.equals(m3)); 
    assertEquals("From: Merkinta line: 334", false, m3.equals(m2)); 
  } // Generated by ComTest END
}