package saalispaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import saalispaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.29 20:22:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SaalisTest {


  // Generated by ComTest BEGIN
  /** testAnna90 */
  @Test
  public void testAnna90() {    // Saalis: 90
    Saalis s = new Saalis(); 
    s.parse("   1   |  4  |   Hauki  | 7.5 | 56 | Lusikka  "); 
    assertEquals("From: Saalis line: 93", "1", s.anna(0)); 
    assertEquals("From: Saalis line: 94", "4", s.anna(1)); 
    assertEquals("From: Saalis line: 95", "Hauki", s.anna(2)); 
    assertEquals("From: Saalis line: 96", "7.5", s.anna(3)); 
    assertEquals("From: Saalis line: 97", "56.0", s.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta129 */
  @Test
  public void testAseta129() {    // Saalis: 129
    Saalis s = new Saalis(); 
    assertEquals("From: Saalis line: 131", null, s.aseta(2,"Hauki")); 
    assertEquals("From: Saalis line: 132", null, s.aseta(3,"9")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi222 */
  @Test
  public void testRekisteroi222() {    // Saalis: 222
    Saalis hauki1 = new Saalis(); 
    assertEquals("From: Saalis line: 224", 0, hauki1.getTunnusNro()); 
    hauki1.rekisteroi(); 
    Saalis hauki2 = new Saalis(); 
    hauki2.rekisteroi(); 
    int n1 = hauki1.getTunnusNro(); 
    int n2 = hauki2.getTunnusNro(); 
    assertEquals("From: Saalis line: 230", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString271 */
  @Test
  public void testToString271() {    // Saalis: 271
    Saalis saalis = new Saalis(); 
    saalis.parse("   1   |  1  |   hauki  | 5.6 | 68.0 | Räsänen  "); 
    assertEquals("From: Saalis line: 274", "1|1|hauki|5.6|68.0|Räsänen", saalis.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse296 */
  @Test
  public void testParse296() {    // Saalis: 296
    Saalis saalis = new Saalis(); 
    saalis.parse("   1   |  7  |   hauki  | 5.6 | 68.0 | Räsänen  "); 
    assertEquals("From: Saalis line: 299", 7, saalis.getMerkintaNro()); 
    assertEquals("From: Saalis line: 300", "1|7|hauki|5.6|68.0|Räsänen", saalis.toString()); 
    saalis.rekisteroi(); 
    int n = saalis.getTunnusNro(); 
    saalis.parse(""+(n+1)); 
    saalis.rekisteroi(); 
    assertEquals("From: Saalis line: 306", n+1+1, saalis.getTunnusNro()); 
    assertEquals("From: Saalis line: 307", "" + (n+1+1) + "|7||5.6|68.0|", saalis.toString());  //Aiemmin testi kirjoitettu väärin, toimi niin kuin pitikin
  } // Generated by ComTest END
}